/**
 * Flowtype definitions for CardSheet
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.17.0
 */

import * as React from "react";
import { View, ViewProps } from "react-native";
declare var _default: React.ForwardRefExoticComponent<{
  ...ViewProps,
  ...{
    enabled: boolean,
    layout: {
      width: number,
      height: number,
      ...
    },
    children: React.Node,
    ...
  },
  ...React.RefAttributes<View>,
}>;
declare export default typeof _default;
