/**
 * Flowtype definitions for HeaderBackButton
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.17.0
 */

import type { StackHeaderLeftButtonProps } from "../../types";
declare type Props = StackHeaderLeftButtonProps;
declare export default function HeaderBackButton(x: Props): React$Node;
declare export {};
