/**
 * Flowtype definitions for TransitionPresets
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.17.0
 */

import type { TransitionPreset } from "../types";

/**
 * Standard iOS navigation transition.
 */
declare export var SlideFromRightIOS: TransitionPreset;
/**
 * Standard iOS navigation transition for modals.
 */
declare export var ModalSlideFromBottomIOS: TransitionPreset;
/**
 * Standard iOS modal presentation style (introduced in iOS 13).
 */
declare export var ModalPresentationIOS: TransitionPreset;
/**
 * Standard Android navigation transition when opening or closing an Activity on Android < 9 (Oreo).
 */
declare export var FadeFromBottomAndroid: TransitionPreset;
/**
 * Standard Android navigation transition when opening or closing an Activity on Android 9 (Pie).
 */
declare export var RevealFromBottomAndroid: TransitionPreset;
/**
 * Standard Android navigation transition when opening or closing an Activity on Android 10 (Q).
 */
declare export var ScaleFromCenterAndroid: TransitionPreset;
/**
 * Default navigation transition for the current platform.
 */
declare export var DefaultTransition: TransitionPreset;
/**
 * Default modal transition for the current platform.
 */
declare export var ModalTransition: TransitionPreset;
