/**
 * Flowtype definitions for KeyboardManager
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.17.0
 */

import * as React from "react";
declare type Props = {
  enabled: boolean,
  children: (props: {
    onPageChangeStart: () => void,
    onPageChangeConfirm: (force: boolean) => void,
    onPageChangeCancel: () => void,
    ...
  }) => React.Node,
  ...
};
declare export default class KeyboardManager mixins React.Component<Props> {
  componentWillUnmount(): void;
  render(): React.Node;
}
declare export {};
