/**
 * Flowtype definitions for MaskedView
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.17.0
 */

import * as React from "react";
declare type Props = {
  maskElement: React.Element<>,
  children: React.Element<>,
  ...
};
declare export default function MaskedView(
  x: Props
): React.Element<
  any,
  | string
  | ((
      props: any
    ) => React.Element<
      any,
      string | any | ((props: any) => React.Component<any, any, any>)
    > | null)
  | ((props: any) => React.Component<any, any, any>)
>;
declare export {};
