/**
 * Flowtype definitions for MaskedViewNative
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.17.0
 */

import * as React from "react";
declare type MaskedViewType = $PropertyType<
  $Exports<"@react-native-community/masked-view">,
  "default"
>;
declare type Props = {
  ...React.ComponentProps<MaskedViewType>,
  ...{
    children: React.Element<>,
    ...
  },
};
declare export default function MaskedView(x: Props): React$Node;
declare export {};
