/**
 * Flowtype definitions for SafeAreaProviderCompat
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.17.0
 */

import * as React from "react";
declare type Props = {
  children: React.Node,
  ...
};
declare export default function SafeAreaProviderCompat(x: Props): React$Node;
declare export {};
