/**
 * Flowtype definitions for TouchableItem
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.17.0
 */

import * as React from "react";
import { ViewProps } from "react-native";
export type Props = {
  ...ViewProps,
  ...{
    pressColor?: string,
    disabled?: boolean,
    borderless?: boolean,
    delayPressIn?: number,
    onPress?: () => void,
    children: React.Node,
    ...
  },
};
declare export default function TouchableItem(x: Props): React$Node;
