/**
 * Flowtype definitions for TouchableItem.ios
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.17.0
 */

import * as React from "react";
import { BaseButton } from "react-native-gesture-handler";
declare type Props = {
  ...React.ComponentProps<typeof BaseButton>,
  ...{
    pressOpacity: number,
    ...
  },
};
declare export default class TouchableItem mixins React.Component<Props> {
  static defaultProps: {
    pressOpacity: number,
    borderless: boolean,
    enabled: boolean,
    ...
  };
  render(): React$Node;
}
declare export {};
