#!/usr/bin/env node
/**
 * Rebuild our custom icon font.
 *
 * TODO WORK HERE write up how to add/update icons
 */

/* eslint-env node */

const fs = require('fs');
const os = require('os');
const webfontsGenerator = require('@vusion/webfonts-generator');

/**
 * The list of icons we use from `@zulip/shared/icons`.
 *
 * To use more such icons, just edit this and rerun.
 */
// TODO: Just compute this automatically to include all the shared icons;
//   it's a short list, and that saves a step in using a new one.
const iconNames = ['globe'];

// TODO use root dir, not cwd

const destDir = 'static/assets/fonts';
const fontName = 'zulip-icons';

async function main() {
  const tmpDir = fs.mkdtempSync(`${os.tmpdir()}/build-icon-font-`);

  // This gets mutated by `webfonts-generator` to tell us the generated mapping.
  const codepoints = {};

  await new Promise((resolve, reject) =>
    webfontsGenerator(
      {
        dest: tmpDir,
        codepoints,
        fontName,
        files: iconNames.map(name => require.resolve(`@zulip/shared/icons/${name}.svg`)),

        types: ['ttf'],
        css: false,
        // Useful for debugging:
        //   html: true,
      },
      err => (err ? reject(err) : resolve()),
    ),
  );

  /* eslint-disable-next-line no-useless-concat */
  const generatedMarker = '@' + 'generated';

  fs.copyFileSync(`${tmpDir}/${fontName}.ttf`, `${destDir}/${fontName}.ttf`);
  fs.writeFileSync(
    `${destDir}/${fontName}.map.js`,
    `/*
 * This file is ${generatedMarker} -- do not edit.
 * To make changes, see tools/build-icon-font.
 * @flow strict
 */
export default ${JSON.stringify(codepoints)};
`,
  );
}

main();
